-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKIgOU60rBvCJ/Tfk
qPSzcnmqLllhmkGmq2PE4jOtdeegCgYIKoZIzj0DAQehRANCAARTi4lnIEvAJbn5
oUpdvmPALrllcBTEb9p2jC73f3P2TuVI0BXHd/XZDMqsQc5jYSp7nbtAP4XUN5Bu
Vbx+0Bb2
-----END PRIVATE KEY-----